# Copyright (c) 2022, NVIDIA CORPORATION.

[build-system]

requires = [
    "wheel",
    "setuptools",
    "scikit-build>=0.13.1",
    "ninja",
]

[tool.pytest.ini_options]
testpaths = ["cugraph_pyg/tests"]
