# Copyright (c) 2023, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: cugraph-dgl
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}

requirements:
  host:
    - python
  run:
    - cugraph ={{ version }}
    - dgl >=1.1.0.cu*
    - numba >=0.57
    - numpy >=1.21
    - pylibcugraphops ={{ minor_version }}
    - python
    - pytorch

tests:
  imports:
    - cugraph_dgl

about:
  home: https://rapids.ai/
  dev_url: https://github.com/rapidsai/cugraph
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: cuGraph library
