# Copyright (c) 2022, NVIDIA CORPORATION.

# Usage:
#   conda build -c rapidsai -c conda-forge -c nvidia .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', 'unknown').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set py_version=environ.get('CONDA_PY', 36) %}
package:
  name: cugraph-pyg
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PARALLEL_LEVEL
  preserve_egg_dir: True

requirements:
  build:
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - python x.x
    - cython>=0.29,<0.30
    - scikit-build>=0.13.1
    # FIXME: this pin can be removed once we move to the GitHub Actions build process
    - setuptools<=65.2.0
  run:
    - distributed>=2022.12.0
    - numba>=0.56.2
    - numpy
    - pytorch
    - cudatoolkit {{ cuda_version }}.*
    # - pyg (uncomment once pyg 2.2 is released)

tests:                                 # [linux64]
  imports:                             # [linux64]
    - cugraph_pyg                      # [linux64]
    # - cugraph_service (uncomment once cugraph-service int. tests ready)

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: cuGraph-pyg library
