# Copyright (c) 2022-2024, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: cugraph-pyg
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PARALLEL_LEVEL

requirements:
  build:
    - {{ stdlib("c") }}
  host:
    - cython >=3.0.0
    - python
    - scikit-build-core >=0.7.0
  run:
    - rapids-dask-dependency ={{ minor_version }}
    - numba >=0.57
    - numpy >=1.23,<2.0a0
    - python
    - pytorch >=2.0
    - cupy >=12.0.0
    - cugraph ={{ version }}
    - pylibcugraphops ={{ minor_version }}
    - pyg >=2.5,<2.6

tests:
  imports:
    - cugraph_pyg

about:
  home: https://rapids.ai/
  dev_url: https://github.com/rapidsai/cugraph
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: cuGraph-pyg library
