# Copyright (c) 2018-2021, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c conda-forge .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
package:
  name: libcugraph
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - CCACHE_DIR
    - CCACHE_NOHASHDIR
    - CCACHE_COMPILERCHECK
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER

requirements:
  build:
    - cmake>=3.20.1
    - cudatoolkit {{ cuda_version }}.*
    - librmm {{ minor_version }}.*
    - cudf {{ minor_version }}.*
    - boost-cpp>=1.66
    - nccl>=2.9.9
    - ucx-proc=*=gpu
    - gtest
    - gmock
    - faiss-proc=*=cuda
    - libfaiss 1.7.0 *_cuda
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}
    - nccl>=2.9.9
    - ucx-proc=*=gpu
    - faiss-proc=*=cuda
    - libfaiss 1.7.0 *_cuda
    - libcusolver>=11.2.1

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: libcugraph library
