# Copyright (c) 2018-2024, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: libcugraph-split

source:
  path: ../../..

build:
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=libcugraph-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcugraph-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS

requirements:
  build:
    - {{ compiler('c') }}
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }} {{ cuda_version }}
    {% else %}
    - {{ compiler('cuda') }}
    {% endif %}
    - cuda-version ={{ cuda_version }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake_version }}
    - ninja
    - openmpi # Required for building cpp-mgtests (multi-GPU tests)
    - {{ stdlib("c") }}
  host:
    {% if cuda_major == "11" %}
    - cudatoolkit
    - cuda-nvtx ={{ cuda_version }}
    - cuda-profiler-api {{ cuda11_cuda_profiler_api_host_version }}
    - libcublas {{ cuda11_libcublas_host_version }}
    - libcublas-dev {{ cuda11_libcublas_host_version }}
    - libcurand {{ cuda11_libcurand_host_version }}
    - libcurand-dev {{ cuda11_libcurand_host_version }}
    - libcusolver {{ cuda11_libcusolver_host_version }}
    - libcusolver-dev {{ cuda11_libcusolver_host_version }}
    - libcusparse {{ cuda11_libcusparse_host_version }}
    - libcusparse-dev {{ cuda11_libcusparse_host_version }}
    {% else %}
    - cuda-nvtx-dev
    - cuda-profiler-api
    - cuda-cudart-dev
    - libcublas-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    {% endif %}
    - cuda-version ={{ cuda_version }}
    - doxygen {{ doxygen_version }}
    - libcudf ={{ minor_version }}
    - libcugraphops ={{ minor_version }}
    - libraft ={{ minor_version }}
    - libraft-headers ={{ minor_version }}
    - librmm ={{ minor_version }}
    - nccl {{ nccl_version }}
    - ucx-proc=*=gpu
    - rapids-build-backend>=0.3.1,<0.4.0.dev0

outputs:
  - name: libcugraph
    version: {{ version }}
    script: install_libcugraph.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
        {% endif %}
    requirements:
      build:
        - cmake {{ cmake_version }}
      host:
        - cuda-version ={{ cuda_version }}
        - cuda-cudart-dev
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_run_version }}
        - cudatoolkit
        - libcublas {{ cuda11_libcublas_run_version }}
        - libcurand {{ cuda11_libcurand_run_version }}
        - libcusolver {{ cuda11_libcusolver_run_version }}
        - libcusparse {{ cuda11_libcusparse_run_version }}
        {% else %}
        - cuda-profiler-api
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
       {% endif %}
        - libcugraphops ={{ minor_version }}
        - libraft ={{ minor_version }}
        - libraft-headers ={{ minor_version }}
        - librmm ={{ minor_version }}
        - nccl {{ nccl_version }}
        - ucx-proc=*=gpu
    about:
      home: https://rapids.ai/
      dev_url: https://github.com/rapidsai/cugraph
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph library
  - name: libcugraph_etl
    version: {{ version }}
    script: install_libcugraph_etl.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
        {% endif %}
    requirements:
      build:
        - cmake {{ cmake_version }}
      host:
        - cuda-version ={{ cuda_version }}
        - cuda-cudart-dev
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        - {{ pin_subpackage('libcugraph', exact=True) }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        {% else %}
        - cuda-cudart
        {% endif %}
        - libcudf ={{ minor_version }}
        - librmm ={{ minor_version }}
    about:
      home: https://rapids.ai/
      dev_url: https://github.com/rapidsai/cugraph
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph_etl library
  - name: libcugraph-tests
    version: {{ version }}
    script: install_libcugraph_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
        {% endif %}
    requirements:
      build:
        - cmake {{ cmake_version }}
      host:
        - cuda-version ={{ cuda_version }}
        - cuda-cudart-dev
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        - {{ pin_subpackage('libcugraph_etl', exact=True) }}
        - {{ pin_subpackage('libcugraph', exact=True) }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        {% else %}
        - cuda-cudart
        {% endif %}
    about:
      home: https://rapids.ai/
      dev_url: https://github.com/rapidsai/cugraph
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph test & benchmark executables
