# Copyright (c) 2018-2022, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c conda-forge .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ.get('CUDA', '11.5').split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0

package:
  name: libcugraph-split

source:
  git_url: ../../..

build:
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=libcugraph-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcugraph-linux64 # [linux64]
    - SCCACHE_BUCKET=rapids-sccache
    - SCCACHE_REGION=us-west-2
    - SCCACHE_IDLE_TIMEOUT=32768

requirements:
  build:
    - cmake {{ cmake_version }}
  host:
    - doxygen {{ doxygen_version }}
    - cudatoolkit {{ cuda_version }}.*
    - libraft-headers {{ minor_version }}.*
    - libcugraphops {{ minor_version }}.*
    - librmm {{ minor_version }}.*
    - cudf {{ minor_version }}.*
    - boost-cpp {{ boost_cpp_version }}
    - nccl {{ nccl_version }}
    - ucx-proc=*=gpu
    - gtest {{ gtest_version }}  # FIXME: pinned to version in https://github.com/rapidsai/integration/blob/branch-22.04/conda/recipes/versions.yaml
    - gmock {{ gtest_version }}  # FIXME: pinned to version in https://github.com/rapidsai/integration/blob/branch-22.04/conda/recipes/versions.yaml

outputs:
  - name: libcugraph
    version: {{ version }}
    script: install_libcugraph.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - cudatoolkit {{ cuda_spec }}
        - libraft-headers {{ minor_version }}
        - librmm {{ minor_version }}
        - nccl {{ nccl_version }}
        - ucx-proc=*=gpu
        - libcugraphops {{ minor_version }}
        - libcusolver {{ libcusolver_version }}
    about:
      home: http://rapids.ai/
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph library
  - name: libcugraph_etl
    version: {{ version }}
    script: install_libcugraph_etl.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - {{ pin_subpackage('libcugraph', exact=True) }}
        - cudatoolkit {{ cuda_spec }}
        - libcudf {{ minor_version }}
        - libraft-headers {{ minor_version }}
        - librmm {{ minor_version }}
    about:
      home: http://rapids.ai/
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph_etl library
  - name: libcugraph-tests
    version: {{ version }}
    script: install_libcugraph_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - {{ pin_subpackage('libcugraph', exact=True) }}
        - {{ pin_subpackage('libcugraph_etl', exact=True) }}
        - cudatoolkit {{ cuda_spec }}
        - gtest {{ gtest_version }}
        - gmock {{ gtest_version }}
    about:
      home: http://rapids.ai/
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph test & benchmark executables
