# Copyright (c) 2018-2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: libcugraph-split

source:
  git_url: ../../..

build:
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=libcugraph-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcugraph-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS

requirements:
  build:
    - {{ compiler('c') }}
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }} {{ cuda_version }}
    {% else %}
    - {{ compiler('cuda') }} {{ cuda_version }}
    - cuda-cudart {{ cuda_version }}
    - cuda-cudart-dev {{ cuda_version }}
    - cuda-cudart-static {{ cuda_version }}
    {% endif %}
    - {{ compiler('cxx') }}
    - cmake {{ cmake_version }}
    - ninja
    - openmpi # Required for building cpp-mgtests (multi-GPU tests)
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - cuda-nvtx ={{ cuda_version }}
    {% if cuda_major == "11" %}
    - cuda-profiler-api {{ cuda11_cuda_profiler_api_host_version }}
    - cudatoolkit ={{ cuda_version }}
    - libcublas {{ cuda11_libcublas_host_version }}
    - libcublas-dev {{ cuda11_libcublas_host_version }}
    - libcurand {{ cuda11_libcurand_host_version }}
    - libcurand-dev {{ cuda11_libcurand_host_version }}
    - libcusolver {{ cuda11_libcusolver_host_version }}
    - libcusolver-dev {{ cuda11_libcusolver_host_version }}
    - libcusparse {{ cuda11_libcusparse_host_version }}
    - libcusparse-dev {{ cuda11_libcusparse_host_version }}
    {% else %}
    - cuda-profiler-api {{ cuda_profiler_api_host_version }}
    - cuda-cudart {{ cuda_version }}
    - cuda-cudart-dev {{ cuda_version }}
    - cuda-cudart-static {{ cuda_version }}
    - libcublas {{ libcublas_host_version }}
    - libcublas-dev {{ libcublas_host_version }}
    - libcurand {{ libcurand_host_version }}
    - libcurand-dev {{ libcurand_host_version }}
    - libcusolver {{ libcusolver_host_version }}
    - libcusolver-dev {{ libcusolver_host_version }}
    - libcusparse {{ libcusparse_host_version }}
    - libcusparse-dev {{ libcusparse_host_version }}
    {% endif %}
    - doxygen {{ doxygen_version }}
    - gmock {{ gtest_version }}
    - gtest {{ gtest_version }}
    - libcudf ={{ minor_version }}*=cuda{{ cuda_major }}*
    - libcugraphops ={{ minor_version }}*=cuda{{ cuda_major }}*
    - libraft ={{ minor_version }}*=cuda{{ cuda_major }}*
    - libraft-headers ={{ minor_version }}*=cuda{{ cuda_major }}*
    - librmm ={{ minor_version }}*=cuda{{ cuda_major }}*
    - nccl {{ nccl_version }}
    - ucx-proc=*=gpu

outputs:
  - name: libcugraph
    version: {{ version }}
    script: install_libcugraph.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_run_version }}
        - cudatoolkit ={{ cuda_version }}
        - libcublas {{ cuda11_libcublas_run_version }}
        - libcublas-dev {{ cuda11_libcublas_run_version }}
        - libcurand {{ cuda11_libcurand_run_version }}
        - libcurand-dev {{ cuda11_libcurand_run_version }}
        - libcusolver {{ cuda11_libcusolver_run_version }}
        - libcusolver-dev {{ cuda11_libcusolver_run_version }}
        - libcusparse {{ cuda11_libcusparse_run_version }}
        - libcusparse-dev {{ cuda11_libcusparse_run_version }}
        {% else %}
        - cuda-profiler-api {{ cuda_profiler_api_run_version }}
        - cuda-cudart {{ cuda_version }}
        - cuda-cudart-dev {{ cuda_version }}
        - cuda-cudart-static {{ cuda_version }}
        - libcublas {{ libcublas_run_version }}
        - libcublas-dev {{ libcublas_run_version }}
        - libcurand {{ libcurand_run_version }}
        - libcurand-dev {{ libcurand_run_version }}
        - libcusolver {{ libcusolver_run_version }}
        - libcusolver-dev {{ libcusolver_run_version }}
        - libcusparse {{ libcusparse_run_version }}
        - libcusparse-dev {{ libcusparse_run_version }}
       {% endif %}
        - libcugraphops ={{ minor_version }}*=cuda{{ cuda_major }}*
        - libraft ={{ minor_version }}*=cuda{{ cuda_major }}*
        - libraft-headers ={{ minor_version }}*=cuda{{ cuda_major }}*
        - librmm ={{ minor_version }}*=cuda{{ cuda_major }}*
        - nccl {{ nccl_version }}
        - ucx-proc=*=gpu
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph library
  - name: libcugraph_etl
    version: {{ version }}
    script: install_libcugraph_etl.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - {{ pin_subpackage('libcugraph', exact=True) }}
        {% if cuda_major == "11" %}
        - cudatoolkit {{ cuda_spec }}
        {% else %}
        - cuda-cudart {{ cuda_spec }}
        - cuda-cudart-dev {{ cuda_spec }}
        - cuda-cudart-static {{ cuda_spec }}
        {% endif %}
        - libcudf ={{ minor_version }}*=cuda{{ cuda_major }}*
        - librmm ={{ minor_version }}*=cuda{{ cuda_major }}*
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph_etl library
  - name: libcugraph-tests
    version: {{ version }}
    script: install_libcugraph_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - {{ pin_subpackage('libcugraph_etl', exact=True) }}
        - {{ pin_subpackage('libcugraph', exact=True) }}
        {% if cuda_major == "11" %}
        - cudatoolkit {{ cuda_spec }}
        {% else %}
        - cuda-cudart {{ cuda_spec }}
        - cuda-cudart-dev {{ cuda_spec }}
        - cuda-cudart-static {{ cuda_spec }}
        {% endif %}
        - gmock {{ gtest_version }}
        - gtest {{ gtest_version }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph test & benchmark executables
