# Copyright (c) 2018-2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

recipe:
  name: libcugraph-split

cache:
  source:
    path: ../../..

  build:
    script:
      content: |
        # Remove `-fdebug-prefix-map` line from CFLAGS and CXXFLAGS so the
        # incrementing version number in the compile line doesn't break the
        # cache
        set -x
        export CFLAGS=$(echo $CFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        export CXXFLAGS=$(echo $CXXFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        set +x

        ./build.sh libcugraph libcugraph_etl cpp-mgtests cpp-mtmgtests -n -v --allgpuarch
      secrets:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
      env:
        CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
        CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
        CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
        CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
        PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL") }}
        SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
        SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
        SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
        SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
        SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
        SCCACHE_S3_KEY_PREFIX: libcugraph/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}

  requirements:
    build:
      - ${{ compiler("c") }}
      - ${{ compiler("cxx") }}
      - ${{ compiler("cuda") }} =${{ cuda_version }}
      - cuda-version =${{ cuda_version }}
      - cmake ${{ cmake_version }}
      - ninja
      - ${{ stdlib("c") }}
    host:
      - cuda-version =${{ cuda_version }}
      - libcudf =${{ minor_version }}
      - libraft =${{ minor_version }}
      - librmm =${{ minor_version }}
      - libucxx ${{ libucxx_version }}
      - nccl ${{ nccl_version }}
      - openmpi <5.0.3 # Required for building cpp-mgtests (multi-GPU tests)
      - rapids-build-backend >=0.3.1,<0.4.0.dev0
      - if: cuda_major == "11"
        then:
          - cudatoolkit
          - cuda-nvtx =${{ cuda_version }}
          - cuda-profiler-api ${{ cuda11_cuda_profiler_api_host_version }}
          - libcublas ${{ cuda11_libcublas_host_version }}
          - libcublas-dev ${{ cuda11_libcublas_host_version }}
          - libcurand ${{ cuda11_libcurand_host_version }}
          - libcurand-dev ${{ cuda11_libcurand_host_version }}
          - libcusolver ${{ cuda11_libcusolver_host_version }}
          - libcusolver-dev ${{ cuda11_libcusolver_host_version }}
          - libcusparse ${{ cuda11_libcusparse_host_version }}
          - libcusparse-dev ${{ cuda11_libcusparse_host_version }}
        else:
          - cuda-nvtx-dev
          - cuda-profiler-api
          - cuda-cudart-dev
          - libcublas-dev
          - libcurand-dev
          - libcusolver-dev
          - libcusparse-dev

outputs:
  - package:
      name: libcugraph
      version: ${{ version }}
    build:
      script:
        content: |
          cmake --install cpp/build
      dynamic_linking:
        overlinking_behavior: "error"
      prefix_detection:
        ignore:
          # See https://github.com/rapidsai/build-planning/issues/160
          - lib/libcugraph.so
          - lib/libcugraph_c.so
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - cuda-version =${{ cuda_version }}
        - librmm =${{ minor_version }}
        - rapids-logger =0.1
        - if: cuda_major == "11"
          then:
            - cudatoolkit
            - libcublas-dev ${{ cuda11_libcublas_host_version }}
            - libcurand-dev ${{ cuda11_libcurand_host_version }}
            - libcusolver-dev ${{ cuda11_libcusolver_host_version }}
            - libcusparse-dev ${{ cuda11_libcusparse_host_version }}
          else:
            - cuda-cudart-dev
            - libcublas-dev
            - libcurand-dev
            - libcusolver-dev
            - libcusparse-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - libraft =${{ minor_version }}
        - librmm =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - if: cuda_major == "11"
          then:
            - cudatoolkit
            - cuda-profiler-api ${{ cuda11_cuda_profiler_api_run_version }}
            - libcublas ${{ cuda11_libcublas_run_version }}
            - libcurand ${{ cuda11_libcurand_run_version }}
            - libcusolver ${{ cuda11_libcusolver_run_version }}
            - libcusparse ${{ cuda11_libcusparse_run_version }}
          else:
            - cuda-profiler-api
            - cuda-cudart
            - libcublas
            - libcurand
            - libcusolver
            - libcusparse
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-nvtx
          - cuda-version
          - libcublas
          - libcudf
          - libcurand
          - libcusolver
          - libcusparse
          - librmm
          - libucxx
          - nccl
          - openmpi
          - if: cuda_major == "11"
            then: cudatoolkit
    about:
      homepage: ${{ load_from_file("python/libcugraph/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libcugraph/pyproject.toml").project.license.text }}
      summary: ${{ load_from_file("python/libcugraph/pyproject.toml").project.description }}

  - package:
      name: libcugraph_etl
      version: ${{ version }}
    build:
      script:
        content: |
          cmake --install cpp/libcugraph_etl/build
      dynamic_linking:
        overlinking_behavior: "error"
      prefix_detection:
        ignore:
          # See https://github.com/rapidsai/build-planning/issues/160
          - lib/libcugraph_etl.so
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - cuda-version =${{ cuda_version }}
        - libcudf =${{ minor_version }}
        - librmm =${{ minor_version }}
        - if: cuda_major == "11"
          then: cudatoolkit
          else: cuda-cudart-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - ${{ pin_subpackage("libcugraph", exact=True) }}
        - libcudf =${{ minor_version }}
        - librmm =${{ minor_version }}
        - if: cuda_major == "11"
          then: cudatoolkit
          else: cuda-cudart
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-nvtx
          - cuda-version
          - libcublas
          - libcudf
          - libcurand
          - libcusolver
          - libcusparse
          - librmm
          - libucxx
          - nccl
          - openmpi
          - if: cuda_major == "11"
            then: cudatoolkit
    about:
      homepage: ${{ load_from_file("python/libcugraph/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libcugraph/pyproject.toml").project.license.text }}
      summary: libcugraph_etl library

  - package:
      name: libcugraph-tests
      version: ${{ version }}
    build:
      script:
        content: |
          cmake --install cpp/build --component testing
          cmake --install cpp/build --component testing_c
          cmake --install cpp/build --component testing_mg
          cmake --install cpp/libcugraph_etl/build --component testing
      dynamic_linking:
        overlinking_behavior: "error"
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - ${{ pin_subpackage("libcugraph", exact=True) }}
        - cuda-version =${{ cuda_version }}
        - nccl ${{ nccl_version }}
        - openmpi <5.0.3 # Required for building cpp-mgtests (multi-GPU tests)
        - rapids-logger =0.1
        - if: cuda_major == "11"
          then: cudatoolkit
          else: cuda-cudart-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - ${{ pin_subpackage("libcugraph", exact=True) }}
        - ${{ pin_subpackage("libcugraph_etl", exact=True) }}
        - if: cuda_major == "11"
          then: cudatoolkit
          else: cuda-cudart
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-nvtx
          - cuda-version
          - libcublas
          - libcudf
          - libcurand
          - libcusolver
          - libcusparse
          - librmm
          - libucxx
          - nccl
          - openmpi
          - if: cuda_major == "11"
            then: cudatoolkit
    about:
      homepage: ${{ load_from_file("python/libcugraph/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libcugraph/pyproject.toml").project.license.text }}
      summary: libcugraph test & benchmark executables
