# CMake generated Testfile for 
# Source directory: /work/cugraph/cpp/tests
# Build directory: /work/cugraph/cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(GRAPH_GENERATORS_TEST "/work/cugraph/cpp/tests/GRAPH_GENERATORS_TEST")
set_tests_properties(GRAPH_GENERATORS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;199;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(ERDOS_RENYI_GENERATOR_TEST "/work/cugraph/cpp/tests/ERDOS_RENYI_GENERATOR_TEST")
set_tests_properties(ERDOS_RENYI_GENERATOR_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;203;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(LEGACY_BETWEENNESS_TEST "/work/cugraph/cpp/tests/LEGACY_BETWEENNESS_TEST")
set_tests_properties(LEGACY_BETWEENNESS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;207;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(LEGACY_EDGE_BETWEENNESS_TEST "/work/cugraph/cpp/tests/LEGACY_EDGE_BETWEENNESS_TEST")
set_tests_properties(LEGACY_EDGE_BETWEENNESS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;208;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(LEGACY_BFS_TEST "/work/cugraph/cpp/tests/LEGACY_BFS_TEST")
set_tests_properties(LEGACY_BFS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;212;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(LOUVAIN_TEST "/work/cugraph/cpp/tests/LOUVAIN_TEST")
set_tests_properties(LOUVAIN_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;216;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(LEIDEN_TEST "/work/cugraph/cpp/tests/LEIDEN_TEST")
set_tests_properties(LEIDEN_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;220;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(ECG_TEST "/work/cugraph/cpp/tests/ECG_TEST")
set_tests_properties(ECG_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;224;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(BALANCED_TEST "/work/cugraph/cpp/tests/BALANCED_TEST")
set_tests_properties(BALANCED_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;228;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(EGO_TEST "/work/cugraph/cpp/tests/EGO_TEST")
set_tests_properties(EGO_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;232;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(LEGACY_FA2_TEST "/work/cugraph/cpp/tests/LEGACY_FA2_TEST")
set_tests_properties(LEGACY_FA2_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;236;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CONNECT_TEST "/work/cugraph/cpp/tests/CONNECT_TEST")
set_tests_properties(CONNECT_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;240;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(SCC_TEST "/work/cugraph/cpp/tests/SCC_TEST")
set_tests_properties(SCC_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;244;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(HUNGARIAN_TEST "/work/cugraph/cpp/tests/HUNGARIAN_TEST")
set_tests_properties(HUNGARIAN_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;248;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(MST_TEST "/work/cugraph/cpp/tests/MST_TEST")
set_tests_properties(MST_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;252;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(STREAM_TEST "/work/cugraph/cpp/tests/STREAM_TEST")
set_tests_properties(STREAM_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;256;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(GENERATE_RMAT_TEST "/work/cugraph/cpp/tests/GENERATE_RMAT_TEST")
set_tests_properties(GENERATE_RMAT_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;260;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(GRAPH_MASK_TEST "/work/cugraph/cpp/tests/GRAPH_MASK_TEST")
set_tests_properties(GRAPH_MASK_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;264;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(SYMMETRIZE_TEST "/work/cugraph/cpp/tests/SYMMETRIZE_TEST")
set_tests_properties(SYMMETRIZE_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;268;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(TRANSPOSE_TEST "/work/cugraph/cpp/tests/TRANSPOSE_TEST")
set_tests_properties(TRANSPOSE_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;272;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(TRANSPOSE_STORAGE_TEST "/work/cugraph/cpp/tests/TRANSPOSE_STORAGE_TEST")
set_tests_properties(TRANSPOSE_STORAGE_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;276;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(WEIGHT_SUM_TEST "/work/cugraph/cpp/tests/WEIGHT_SUM_TEST")
set_tests_properties(WEIGHT_SUM_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;280;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(DEGREE_TEST "/work/cugraph/cpp/tests/DEGREE_TEST")
set_tests_properties(DEGREE_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;284;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(COUNT_SELF_LOOPS_AND_MULTI_EDGES_TEST "/work/cugraph/cpp/tests/COUNT_SELF_LOOPS_AND_MULTI_EDGES_TEST")
set_tests_properties(COUNT_SELF_LOOPS_AND_MULTI_EDGES_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;288;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(COARSEN_GRAPH_TEST "/work/cugraph/cpp/tests/COARSEN_GRAPH_TEST")
set_tests_properties(COARSEN_GRAPH_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;293;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(INDUCED_SUBGRAPH_TEST "/work/cugraph/cpp/tests/INDUCED_SUBGRAPH_TEST")
set_tests_properties(INDUCED_SUBGRAPH_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;297;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(BFS_TEST "/work/cugraph/cpp/tests/BFS_TEST")
set_tests_properties(BFS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;301;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(EXTRACT_BFS_PATHS_TEST "/work/cugraph/cpp/tests/EXTRACT_BFS_PATHS_TEST")
set_tests_properties(EXTRACT_BFS_PATHS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;305;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(MSBFS_TEST "/work/cugraph/cpp/tests/MSBFS_TEST")
set_tests_properties(MSBFS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;310;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(SSSP_TEST "/work/cugraph/cpp/tests/SSSP_TEST")
set_tests_properties(SSSP_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;314;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(HITS_TEST "/work/cugraph/cpp/tests/HITS_TEST")
set_tests_properties(HITS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;318;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(PAGERANK_TEST "/work/cugraph/cpp/tests/PAGERANK_TEST")
set_tests_properties(PAGERANK_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;322;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(KATZ_CENTRALITY_TEST "/work/cugraph/cpp/tests/KATZ_CENTRALITY_TEST")
set_tests_properties(KATZ_CENTRALITY_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;326;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(EIGENVECTOR_CENTRALITY_TEST "/work/cugraph/cpp/tests/EIGENVECTOR_CENTRALITY_TEST")
set_tests_properties(EIGENVECTOR_CENTRALITY_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;330;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(BETWEENNESS_CENTRALITY_TEST "/work/cugraph/cpp/tests/BETWEENNESS_CENTRALITY_TEST")
set_tests_properties(BETWEENNESS_CENTRALITY_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;334;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(EDGE_BETWEENNESS_CENTRALITY_TEST "/work/cugraph/cpp/tests/EDGE_BETWEENNESS_CENTRALITY_TEST")
set_tests_properties(EDGE_BETWEENNESS_CENTRALITY_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;335;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(WEAKLY_CONNECTED_COMPONENTS_TEST "/work/cugraph/cpp/tests/WEAKLY_CONNECTED_COMPONENTS_TEST")
set_tests_properties(WEAKLY_CONNECTED_COMPONENTS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;339;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(SIMILARITY_TEST "/work/cugraph/cpp/tests/SIMILARITY_TEST")
set_tests_properties(SIMILARITY_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;343;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(RANDOM_WALKS_TEST "/work/cugraph/cpp/tests/RANDOM_WALKS_TEST")
set_tests_properties(RANDOM_WALKS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;348;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(UNIFORM_NEIGHBOR_SAMPLING_TEST "/work/cugraph/cpp/tests/UNIFORM_NEIGHBOR_SAMPLING_TEST")
set_tests_properties(UNIFORM_NEIGHBOR_SAMPLING_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;352;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(RENUMBERING_TEST "/work/cugraph/cpp/tests/RENUMBERING_TEST")
set_tests_properties(RENUMBERING_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;360;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CORE_NUMBER_TEST "/work/cugraph/cpp/tests/CORE_NUMBER_TEST")
set_tests_properties(CORE_NUMBER_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;364;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(K_CORE_TEST "/work/cugraph/cpp/tests/K_CORE_TEST")
set_tests_properties(K_CORE_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;368;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(TRIANGLE_COUNT_TEST "/work/cugraph/cpp/tests/TRIANGLE_COUNT_TEST")
set_tests_properties(TRIANGLE_COUNT_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;372;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(K_HOP_NBRS_TEST "/work/cugraph/cpp/tests/K_HOP_NBRS_TEST")
set_tests_properties(K_HOP_NBRS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;73;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;376;ConfigureTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_CREATE_GRAPH_TEST "/work/cugraph/cpp/tests/CAPI_CREATE_GRAPH_TEST")
set_tests_properties(CAPI_CREATE_GRAPH_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;638;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_PAGERANK_TEST "/work/cugraph/cpp/tests/CAPI_PAGERANK_TEST")
set_tests_properties(CAPI_PAGERANK_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;639;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_KATZ_TEST "/work/cugraph/cpp/tests/CAPI_KATZ_TEST")
set_tests_properties(CAPI_KATZ_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;640;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_EIGENVECTOR_CENTRALITY_TEST "/work/cugraph/cpp/tests/CAPI_EIGENVECTOR_CENTRALITY_TEST")
set_tests_properties(CAPI_EIGENVECTOR_CENTRALITY_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;641;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_BETWEENNESS_CENTRALITY_TEST "/work/cugraph/cpp/tests/CAPI_BETWEENNESS_CENTRALITY_TEST")
set_tests_properties(CAPI_BETWEENNESS_CENTRALITY_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;642;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_HITS_TEST "/work/cugraph/cpp/tests/CAPI_HITS_TEST")
set_tests_properties(CAPI_HITS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;643;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_BFS_TEST "/work/cugraph/cpp/tests/CAPI_BFS_TEST")
set_tests_properties(CAPI_BFS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;644;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_SSSP_TEST "/work/cugraph/cpp/tests/CAPI_SSSP_TEST")
set_tests_properties(CAPI_SSSP_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;645;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_EXTRACT_PATHS_TEST "/work/cugraph/cpp/tests/CAPI_EXTRACT_PATHS_TEST")
set_tests_properties(CAPI_EXTRACT_PATHS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;646;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_NODE2VEC_TEST "/work/cugraph/cpp/tests/CAPI_NODE2VEC_TEST")
set_tests_properties(CAPI_NODE2VEC_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;647;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_WEAKLY_CONNECTED_COMPONENTS_TEST "/work/cugraph/cpp/tests/CAPI_WEAKLY_CONNECTED_COMPONENTS_TEST")
set_tests_properties(CAPI_WEAKLY_CONNECTED_COMPONENTS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;648;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_STRONGLY_CONNECTED_COMPONENTS_TEST "/work/cugraph/cpp/tests/CAPI_STRONGLY_CONNECTED_COMPONENTS_TEST")
set_tests_properties(CAPI_STRONGLY_CONNECTED_COMPONENTS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;649;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_UNIFORM_NEIGHBOR_SAMPLE_TEST "/work/cugraph/cpp/tests/CAPI_UNIFORM_NEIGHBOR_SAMPLE_TEST")
set_tests_properties(CAPI_UNIFORM_NEIGHBOR_SAMPLE_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;650;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_RANDOM_WALKS_TEST "/work/cugraph/cpp/tests/CAPI_RANDOM_WALKS_TEST")
set_tests_properties(CAPI_RANDOM_WALKS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;651;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_TRIANGLE_COUNT_TEST "/work/cugraph/cpp/tests/CAPI_TRIANGLE_COUNT_TEST")
set_tests_properties(CAPI_TRIANGLE_COUNT_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;652;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_LOUVAIN_TEST "/work/cugraph/cpp/tests/CAPI_LOUVAIN_TEST")
set_tests_properties(CAPI_LOUVAIN_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;653;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_CORE_NUMBER_TEST "/work/cugraph/cpp/tests/CAPI_CORE_NUMBER_TEST")
set_tests_properties(CAPI_CORE_NUMBER_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;654;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_SIMILARITY_TEST "/work/cugraph/cpp/tests/CAPI_SIMILARITY_TEST")
set_tests_properties(CAPI_SIMILARITY_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;655;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_K_CORE_TEST "/work/cugraph/cpp/tests/CAPI_K_CORE_TEST")
set_tests_properties(CAPI_K_CORE_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;656;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_INDUCED_SUBGRAPH_TEST "/work/cugraph/cpp/tests/CAPI_INDUCED_SUBGRAPH_TEST")
set_tests_properties(CAPI_INDUCED_SUBGRAPH_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;657;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_EGONET_TEST "/work/cugraph/cpp/tests/CAPI_EGONET_TEST")
set_tests_properties(CAPI_EGONET_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;658;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
add_test(CAPI_TWO_HOP_NEIGHBORS_TEST "/work/cugraph/cpp/tests/CAPI_TWO_HOP_NEIGHBORS_TEST")
set_tests_properties(CAPI_TWO_HOP_NEIGHBORS_TEST PROPERTIES  _BACKTRACE_TRIPLES "/work/cugraph/cpp/tests/CMakeLists.txt;131;add_test;/work/cugraph/cpp/tests/CMakeLists.txt;659;ConfigureCTest;/work/cugraph/cpp/tests/CMakeLists.txt;0;")
