# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c conda-forge -c defaults .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', 36) %}
package:
  name: cugraph
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL

requirements:
  build:
    - python x.x
    - cython>=0.29,<0.30
    - libcugraph={{ version }}
    - cudf={{ minor_version }}
    - ucx-py {{ minor_version }}
    - ucx-proc=*=gpu
  run:
    - python x.x
    - libcugraph={{ version }}
    - cudf={{ minor_version }}
    - dask-cudf {{ minor_version }}
    - dask-cuda {{ minor_version }}
    - dask>=2.12.0
    - distributed>=2.12.0
    - nccl>=2.7
    - ucx-py {{ minor_version }}
    - ucx-proc=*=gpu

#test:
#  commands:
#    - test -f $PREFIX/include/cugraph.h


about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: libcugraph library
