# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cugraph
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  files:
    exclude:
      - '*libarrow.so.*gdb.py'
  prefix_detection:
    # See https://github.com/rapidsai/build-planning/issues/160
    # Blanket ignore here as there are quite a few shared objects shipped in cugraph
    ignore_binary_files: True
  script:
    content: |
      ./build.sh cugraph --allgpuarch
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - SCCACHE_DIST_AUTH_TOKEN
    env:
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      NVCC_APPEND_FLAGS: ${{ env.get("NVCC_APPEND_FLAGS", default="") }}
      PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL", default="8") }}
      RAPIDS_ARTIFACTS_DIR: ${{ env.get("RAPIDS_ARTIFACTS_DIR", default="") }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET", default="") }}
      SCCACHE_DIST_AUTH_TYPE: ${{ env.get("SCCACHE_DIST_AUTH_TYPE", default="token") }}
      SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE: ${{ env.get("SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE", default="false") }}
      SCCACHE_DIST_MAX_RETRIES: ${{ env.get("SCCACHE_DIST_MAX_RETRIES", default="inf") }}
      SCCACHE_DIST_REQUEST_TIMEOUT: ${{ env.get("SCCACHE_DIST_REQUEST_TIMEOUT", default="7140") }}
      SCCACHE_DIST_SCHEDULER_URL: ${{ env.get("SCCACHE_DIST_SCHEDULER_URL", default="") }}
      SCCACHE_ERROR_LOG: ${{ env.get("SCCACHE_ERROR_LOG", default="/tmp/sccache.log") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT", default="0") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION", default="") }}
      SCCACHE_S3_KEY_PREFIX: cugraph/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS", default="false") }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL", default="true") }}
      SCCACHE_SERVER_LOG: ${{ env.get("SCCACHE_SERVER_LOG", default="sccache=debug") }}
requirements:
  build:
    - cmake ${{ cmake_version }}
    - ninja
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("cuda") }}
    - cuda-version =${{ cuda_version }}
    - ${{ stdlib("c") }}
  host:
    - cuda-version =${{ cuda_version }}
    - cudf =${{ minor_version }}
    - cython >=3.1.2
    - libcugraph =${{ version }}
    - pip
    - pylibcudf =${{ minor_version }}
    - pylibraft =${{ minor_version }}
    - python =${{ py_version }}
    - raft-dask =${{ minor_version }}
    - rmm =${{ minor_version }}
    - rapids-build-backend >=0.4.0,<0.5.0.dev0
    - scikit-build-core >=0.10.0
    - cuda-cudart-dev
  run:
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - aiohttp
    - cudf =${{ minor_version }}
    - cupy >=13.6.0
    - dask-cuda =${{ minor_version }}
    - dask-cudf =${{ minor_version }}
    - fsspec>=0.6.0
    - libcugraph =${{ version }}
    - pylibcudf =${{ minor_version }}
    - pylibcugraph =${{ version }}
    - pylibraft =${{ minor_version }}
    - python
    - raft-dask =${{ minor_version }}
    - rapids-dask-dependency =${{ minor_version }}
    - requests
    - ucxx ${{ ucxx_version }}
    - cuda-cudart
    - if: cuda_major == "12"
      then: cuda-python >=12.9.2,<13.0a0
      else: cuda-python >=13.0.1,<14.0a0
  ignore_run_exports:
    from_package:
      - cuda-cudart-dev
    by_name:
      - cuda-version

tests:
  - python:
      imports:
        - cugraph
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cugraph/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cugraph/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/cugraph/pyproject.toml").project.description }}
