# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Documentation - New Documentation Request
description: Request additions to cuGraph's documentation
title: "[DOC]: "
labels: ["doc", "? - Needs Triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help cuGraph and improve our documentation!

  - type: dropdown
    id: criticality
    attributes:
      label: How would you describe the priority of this documentation request
      options:
        - Critical (currently preventing usage)
        - High
        - Medium
        - Low (would be nice)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Describe the future/missing documentation
      placeholder: A code snippet mentions function foo(args) but I cannot find any documentation on it.
    validations:
      required: true

  - type: textarea
    id: search_locs
    attributes:
      label: Where have you looked?
      placeholder: |
       https://docs.rapids.ai/api/cugraph/stable/ and
       https://docs.rapids.ai/api/cugraph/nightly

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://docs.rapids.ai/resources/conduct/)
      options:
        - label: I agree to follow cuGraph's Code of Conduct
          required: true
        - label: I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report
          required: true
