# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Documentation - Correction/Update Request
description: Request corrections or updates to existing cuGraph documentation
title: "[DOC]: "
labels: ["doc", "? - Needs Triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help cuGraph and improve our documentation!

  - type: dropdown
    id: criticality
    attributes:
      label: How would you describe the priority of this documentation request
      options:
        - Critical (currently preventing usage)
        - High
        - Medium
        - Low (would be nice)
    validations:
      required: true

  - type: input
    id: correction_location
    attributes:
      label: Please provide a link or source to the relevant docs
      placeholder: "ex: https://docs.rapids.ai/api/cugraph/stable/api_docs/centrality.html"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Describe the problems in the documentation
      placeholder: The documents say to use foo.func(args) however an AttributeError is thrown
    validations:
      required: true

  - type: textarea
    id: correction
    attributes:
      label: (Optional) Propose a correction
      placeholder: foo.func() was deprecated, replace documentation with foo.new_func()

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://docs.rapids.ai/resources/conduct/)
      options:
        - label: I agree to follow cuGraph's Code of Conduct
          required: true
        - label: I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report
          required: true
