# Copyright (c) 2023-2024, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: nx-cugraph
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}

requirements:
  host:
    - python
    - rapids-build-backend>=0.3.1,<0.4.0.dev0
    - setuptools>=61.0.0
  run:
    - pylibcugraph ={{ version }}
    - networkx >=3.0
    - cupy >=12.0.0
    - python

tests:
  imports:
    - nx_cugraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rapids.ai/
  dev_url: https://github.com/rapidsai/cugraph
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: cuGraph backend for GPU-accelerated NetworkX
