# Copyright (c) 2022, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c conda-forge .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
package:
  name: libcugraph_etl
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=libcugraph-etl-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcugraph-etl-linux64 # [linux64]
    - SCCACHE_BUCKET=rapids-sccache
    - SCCACHE_REGION=us-west-2
    - SCCACHE_IDLE_TIMEOUT=32768

requirements:
  build:
    - cmake>=3.20.1
    - doxygen>=1.8.11
    - cudatoolkit {{ cuda_version }}.*
    - libcugraphops {{ minor_version }}.*  # needed for cmake to find transitive deps
    - libcudf {{ minor_version }}.*
    - libcugraph {{ minor_version }}.*
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}
    - libcudf {{ minor_version }}.*
    - libcugraph {{ minor_version }}.*
    - faiss-proc=*=cuda
    - libfaiss 1.7.0 *_cuda

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: libcugraph_etl library
