# Copyright (c) 2018-2024, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: cugraph-service-split

source:
  path: ../../..

outputs:
  - name: cugraph-service-client
    version: {{ version }}
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
    about:
      home: https://rapids.ai/
      dev_url: https://github.com/rapidsai/cugraph
      license: Apache-2.0
      license_family: APACHE
      license_file: ../../../LICENSE
      summary: cugraph-service client
    script: install_cugraph-service-client.sh
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - thriftpy2 >=0.4.15

  - name: cugraph-service-server
    version: {{ version }}
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
    about:
      home: https://rapids.ai/
      dev_url: https://github.com/rapidsai/cugraph
      license: Apache-2.0
      license_family: APACHE
      license_file: ../../../LICENSE
      summary: cugraph-service server
    script: install_cugraph-service-server.sh
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - {{ pin_subpackage('cugraph-service-client', exact=True) }}
        - cudf ={{ minor_version }}
        - cugraph ={{ minor_version }}
        - cupy >=12.0.0
        - dask-cuda ={{ minor_version }}
        - dask-cudf ={{ minor_version }}
        - numba >=0.57
        - numpy >=1.23,<2.0a0
        - python
        - rapids-dask-dependency ={{ minor_version }}
        - thriftpy2 >=0.4.15
        - ucx-py {{ ucx_py_version }}

tests:
  imports:
    - cugraph_service_server
    - cugraph_service_client
