# Copyright (c) 2018-2022, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c conda-forge  .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set ucx_py_version=environ.get('UCX_PY_VERSION') %}

package:
  name: cugraph-service-split

source:
  git_url: ../../..

outputs:
  - name: cugraph-service-client
    version: {{ version }}
    about:
      home: http://rapids.ai/
      license: Apache-2.0
      license_family: APACHE
      license_file: ../../../LICENSE
      summary: cugraph-service client
    script: install_cugraph-service-client.sh
    requirements:
      host:
        - python x.x
        - pip
        # FIXME: this pin can be removed once we move to the GitHub Actions build process
        - setuptools<=65.2.0
      run:
        - python x.x
        - thriftpy2 >=0.4.15

  - name: cugraph-service-server
    version: {{ version }}
    about:
      home: http://rapids.ai/
      license: Apache-2.0
      license_family: APACHE
      license_file: ../../../LICENSE
      summary: cugraph-service server
    script: install_cugraph-service-server.sh
    requirements:
      host:
        - python x.x
        - pip
        # FIXME: this pin can be removed once we move to the GitHub Actions build process
        - setuptools<=65.2.0
      run:
        - python x.x
        - thriftpy2 >=0.4.15
        - {{ pin_compatible('cugraph-service-client', exact=True) }}
        - {{ pin_compatible('cugraph', exact=True) }}
        - cupy >=9.5.0,<12.0.0a0
        - numpy
        - ucx-py {{ ucx_py_version }}
        - distributed >=2022.12.0
        - dask-cuda {{ minor_version }}.*
        - cudf {{ minor_version }}.*
        - dask-cudf {{ minor_version }}.*

tests:                                 # [linux64]
  imports:                             # [linux64]
    - cugraph_service_server           # [linux64]
    - cugraph_service_client           # [linux64]
