# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: ${{ git.head_rev(".")[:8] }}

recipe:
  name: cugraph-split

cache:
  source:
    path: ../../..

outputs:
  - package:
      name: cugraph-service-client
      version: ${{ version }}
    build:
      string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
      script:
        content: |
          cd python/cugraph-service/client
          python -m pip install \
              --no-build-isolation \
              --no-index \
              --no-deps \
              --ignore-installed \
              -vv \
              .
    requirements:
      host:
        - pip
        - python =${{ py_version }}
        - rapids-build-backend >=0.3.0,<0.4.0.dev0
        - setuptools>=61.0.0
      run:
        - python
        - thriftpy2 >=0.4.15,!=0.5.0,!=0.5.1

    about:
      homepage: ${{ load_from_file("python/cugraph-service/client/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/cugraph-service/client/pyproject.toml").project.license.text }}
      summary: ${{ load_from_file("python/cugraph-service/client/pyproject.toml").project.description }}

  - package:
      name: cugraph-service-server
      version: ${{ version }}
    build:
      string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
      script:
        content: |
          cd python/cugraph-service/server
          python -m pip install \
              --no-build-isolation \
              --no-index \
              --no-deps \
              --ignore-installed \
              --config-settings rapidsai.disable-cuda=true \
              -vv \
              .
    requirements:
      host:
        - pip
        - python =${{ py_version }}
        - rapids-build-backend >=0.3.0,<0.4.0.dev0
        - setuptools>=61.0.0
        - wheel
      run:
        - ${{ pin_subpackage('cugraph-service-client', exact=True) }}
        - cudf =${{ minor_version }}
        - cugraph =${{ minor_version }}
        - cupy >=12.0.0
        - dask-cuda =${{ minor_version }}
        - dask-cudf =${{ minor_version }}
        - numba >=0.59.1,<0.61.0a0
        - numpy >=1.23,<3.0a0
        - python
        - rapids-dask-dependency =${{ minor_version }}
        - thriftpy2 >=0.4.15,!=0.5.0,!=0.5.1
        - ucx-py ${{ ucx_py_version }}

    about:
      homepage: ${{ load_from_file("python/cugraph-service/server/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/cugraph-service/server/pyproject.toml").project.license.text }}
      summary: ${{ load_from_file("python/cugraph-service/server/pyproject.toml").project.description }}
