# Copyright (c) 2022, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c conda-forge  .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', 'unknown').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set py_version=environ.get('CONDA_PY', 36) %}
{% set ucx_py_version=environ.get('UCX_PY_VERSION') %}
package:
  name: pylibcugraph
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL

requirements:
  build:
    - python x.x
    - cython>=0.29,<0.30
    - libcugraph={{ version }}
    - ucx-py {{ ucx_py_version }}
    - ucx-proc=*=gpu
    - cudatoolkit {{ cuda_version }}.*
    - rmm {{ minor_version }}.*
    - libraft-headers {{ minor_version }}
  run:
    - python x.x
    - libraft-headers {{ minor_version }}
    - libcugraph={{ version }}
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}

tests:                                 # [linux64]
  requirements:                        # [linux64]
    - cudatoolkit {{ cuda_version }}.* # [linux64]
  imports:                             # [linux64]
    - pylibcugraph                     # [linux64]

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: pylibcugraph library
