# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: pylibcugraph
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh pylibcugraph
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env:
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
      SCCACHE_S3_KEY_PREFIX: pylibcugraph/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}
requirements:
  build:
    - cmake ${{ cmake_version }}
    - ninja
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("cuda") }}
    - cuda-version =${{ cuda_version }}
    - ${{ stdlib("c") }}
  host:
    - cuda-version =${{ cuda_version }}
    - cython >=3.1.2
    - libcugraph =${{ version }}
    - pip
    - pylibraft =${{ minor_version }}
    - python =${{ py_version }}
    - rapids-build-backend >=0.3.0,<0.4.0.dev0
    - scikit-build-core >=0.10.0
    - if: cuda_major == "11"
      then:
        - cudatoolkit
      else:
        - cuda-cudart-dev
  run:
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - cupy >=12.0.0
    - libcugraph =${{ version }}
    - numpy>=1.23,<3.0a0
    - pylibraft =${{ minor_version }}
    - python
    - rmm =${{ minor_version }}
    - if: cuda_major == "11"
      then:
        - cudatoolkit
      else:
        - cuda-cudart
  ignore_run_exports:
    from_package:
      - if: cuda_major != "11"
        then:
          - cuda-cudart-dev
    by_name:
      - cuda-version
      - if: cuda_major == "11"
        then: cudatoolkit

tests:
  - python:
      imports:
        - pylibcugraph
      pip_check: false

about:
  homepage: ${{ load_from_file("python/pylibcugraph/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/pylibcugraph/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/pylibcugraph/pyproject.toml").project.description }}
