name: build
on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
permissions: {}
jobs:
  cpp-build:
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-build.yaml@release/26.06
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      node_type: cpu16
      script: ci/build_cpp.sh
      sha: ${{ inputs.sha }}
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
  python-build:
    needs: [cpp-build]
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-build.yaml@release/26.06
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      script: ci/build_python.sh
      sha: ${{ inputs.sha }}
      # Build a conda package for each CUDA x ARCH x minimum supported Python version
      matrix_filter: group_by({CUDA_VER, ARCH}) | map(min_by(.PY_VER | split(".") | map(tonumber)))
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
