name: cuGraph wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'
  workflow_call:
    inputs:
      versioneer-override:
        type: string
        default: ''
      build-tag:
        type: string
        default: ''
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string
      build-type:
        type: string
        default: nightly

concurrency:
  group: "cugraph-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pylibcugraph-wheel:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@main
    with:
      repo: rapidsai/cugraph

      build-type: ${{ inputs.build-type }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
      date: ${{ inputs.date }}

      package-dir: python/pylibcugraph
      package-name: pylibcugraph

      python-package-versioneer-override: ${{ inputs.versioneer-override }}
      python-package-build-tag: ${{ inputs.build-tag }}

      skbuild-configure-options: "-DCUGRAPH_RAFT_REPOSITORY=https://github.com/vyasr/raft.git -DCUGRAPH_RAFT_BRANCH=feat/cibuildwheel -DCPM_DOWNLOAD_ALL=ON -DDETECT_CONDA_ENV=OFF -DCUGRAPH_BUILD_WHEELS=ON -DUSE_CUGRAPH_OPS=OFF"

      # Need to install a patched version of the benchmark repo that has the
      # rmm package name patched to rmm-cu11.
      test-before-amd64: "pip install git+https://github.com/vyasr/benchmark.git@versioned_rmm_req#subdirectory=rapids_pytest_benchmark"
      test-before-arm64: "pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64 && pip install git+https://github.com/vyasr/benchmark.git@versioned_rmm_req#subdirectory=rapids_pytest_benchmark"
      test-extras: test

      test-unittest: "RAPIDS_DATASET_ROOT_DIR=`pwd`/datasets pytest -v ./python/pylibcugraph/pylibcugraph/tests"
    secrets: inherit

  cugraph-wheel:
    needs: pylibcugraph-wheel
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@main
    with:
      repo: rapidsai/cugraph

      build-type: ${{ inputs.build-type }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
      date: ${{ inputs.date }}

      package-dir: python/cugraph
      package-name: cugraph

      python-package-versioneer-override: ${{ inputs.versioneer-override }}
      python-package-build-tag: ${{ inputs.build-tag }}

      skbuild-configure-options: "-DCUGRAPH_RAFT_REPOSITORY=https://github.com/vyasr/raft.git -DCUGRAPH_RAFT_BRANCH=feat/cibuildwheel -DCPM_DOWNLOAD_ALL=ON -DDETECT_CONDA_ENV=OFF -DCUGRAPH_BUILD_WHEELS=ON -DUSE_CUGRAPH_OPS=OFF"

      # Need to install a patched version of the benchmark repo that has the
      # rmm package name patched to rmm-cu11.
      test-before-amd64: "pip install git+https://github.com/vyasr/benchmark.git@versioned_rmm_req#subdirectory=rapids_pytest_benchmark"
      test-before-arm64: "pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64 && pip install git+https://github.com/vyasr/benchmark.git@versioned_rmm_req#subdirectory=rapids_pytest_benchmark"
      test-extras: test
      test-unittest: "RAPIDS_DATASET_ROOT_DIR=`pwd`/datasets pytest -v ./python/cugraph/cugraph/tests --benchmark-gpu-disable"
    secrets: inherit
