name: cuGraph wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'

jobs:
  pylibcugraph-wheel:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@feat/wheel-ci-actions-2
    with:
      package-name: pylibcugraph
      package-dir: python/pylibcugraph
      python-package-versioneer-override: "22.10.00a"
      python-package-build-tag: "1"
      python-version: "3.8 3.9"

      manylinux-container-amd64: "rapidsai/manylinux2014"
      manylinux-container-arm64: "rapidsai/manylinux_2_31"

      auditwheel-repair-command-amd64: "auditwheel --verbose repair -w {dest_dir} --plat manylinux_2_17_x86_64 {wheel}"
      auditwheel-repair-command-arm64: "auditwheel --verbose repair -w {dest_dir} --plat manylinux_2_31_aarch64 {wheel}"

      cibw-before-all-amd64: "yum install -y blas-devel lapack-devel"
      cibw-before-all-arm64: "apt-get install -y libblas-dev liblapack-dev"
      cibw-environment: "PIP_INDEX_URL=https://pypi.k8s.rapids.ai/simple"

      skbuild-configure-options: "--log-level=DEBUG -DCUGRAPH_CUGRAPH_OPS_BRANCH=feat/cibuildwheel -DCPM_DOWNLOAD_ALL=ON -DDETECT_CONDA_ENV=OFF -DCUGRAPH_BUILD_WHEELS=ON -DCMAKE_CUDA_ARCHITECTURES=ALL"

      test-container-amd64: "rapidsai/manylinux_2_27"
      test-container-arm64: "rapidsai/manylinux_2_31"
      test-extras:  "test"
      test-requires: "dask[distributed,dataframe]"
      test-before-amd64: "pip install rmm-cu11 cudf-cu11 raft-dask-cu11 pylibraft-cu11 dask-cudf-cu11 --index-url https://pypi.k8s.rapids.ai/simple && pip install cupy-cuda115 && pip install git+https://github.com/rapidsai/asvdb.git@main && pip install git+https://github.com/vyasr/benchmark.git@versioned_rmm_req#subdirectory=rapids_pytest_benchmark"
      test-before-arm64: "pip install rmm-cu11 cudf-cu11 raft-dask-cu11 pylibraft-cu11 dask-cudf-cu11 --index-url https://pypi.k8s.rapids.ai/simple && pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64 &&  pip install git+https://github.com/rapidsai/asvdb.git@main && pip install git+https://github.com/vyasr/benchmark.git@versioned_rmm_req#subdirectory=rapids_pytest_benchmark"
      test-unittest: "RAPIDS_DATASET_ROOT_DIR=`pwd`/datasets pytest -v ./python/pylibcugraph/pylibcugraph/tests"
    secrets: inherit
  cugraph-wheel:
    needs: pylibcugraph-wheel
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@feat/wheel-ci-actions-2
    with:
      package-name: cugraph
      package-dir: python/cugraph
      python-package-versioneer-override: "22.10.00a"
      python-package-build-tag: "1"
      python-version: "3.8 3.9"

      manylinux-container-amd64: "rapidsai/manylinux2014"
      manylinux-container-arm64: "rapidsai/manylinux_2_31"

      auditwheel-repair-command-amd64: "auditwheel --verbose repair -w {dest_dir} --plat manylinux_2_17_x86_64 {wheel}"
      auditwheel-repair-command-arm64: "auditwheel --verbose repair -w {dest_dir} --plat manylinux_2_31_aarch64 {wheel}"

      cibw-before-all-amd64: "yum install -y blas-devel lapack-devel"
      cibw-before-all-arm64: "apt-get install -y libblas-dev liblapack-dev"
      cibw-environment: "PIP_INDEX_URL=https://pypi.k8s.rapids.ai/simple"

      skbuild-configure-options: "--log-level=DEBUG -DCUGRAPH_CUGRAPH_OPS_BRANCH=feat/cibuildwheel -DCPM_DOWNLOAD_ALL=ON -DDETECT_CONDA_ENV=OFF -DCUGRAPH_BUILD_WHEELS=ON -DCMAKE_CUDA_ARCHITECTURES=ALL"

      test-container-amd64: "rapidsai/manylinux_2_27"
      test-container-arm64: "rapidsai/manylinux_2_31"
      test-before-amd64: "pip install rmm-cu11 cudf-cu11 dask-cuda dask-cudf-cu11 raft-dask-cu11 pylibraft-cu11 pylibcugraph-cu11 --index-url https://pypi.k8s.rapids.ai/simple && pip install git+https://github.com/rapidsai/asvdb.git@main && pip install git+https://github.com/vyasr/benchmark.git@versioned_rmm_req#subdirectory=rapids_pytest_benchmark"
      test-before-arm64: "pip install rmm-cu11 cudf-cu11 dask-cuda dask-cudf-cu11 raft-dask-cu11 pylibraft-cu11 pylibcugraph-cu11 --index-url https://pypi.k8s.rapids.ai/simple && pip install git+https://github.com/rapidsai/asvdb.git@main && pip install git+https://github.com/vyasr/benchmark.git@versioned_rmm_req#subdirectory=rapids_pytest_benchmark"
      test-extras:  "test"
      test-requires: "dask[distributed,dataframe]"
      test-unittest: "RAPIDS_DATASET_ROOT_DIR=`pwd`/datasets pytest -v ./python/cugraph/cugraph/tests"
      test-smoketest: "import cudf, cugraph; gdf = cudf.read_csv('graph_data.csv', names=['src', 'dst'], dtype=['int32', 'int32']); G = cugraph.Graph();G.from_cudf_edgelist(gdf, source='src', destination='dst'); df_page = cugraph.pagerank(G); print(df_page.sort_values('pagerank', ascending=False).head(10))"
    secrets: inherit
